spring.application.name=foodFlow

#spring.datasource.url=jdbc:h2:file:./data/foodflowdb
spring.datasource.url=jdbc:h2:file:C:/Users/thous/source/Interview-learning/H2-DataBase/foodflowdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

server.port=8081